# Generated by Django 5.2.17 on 2026-08-13 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyntheticConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_asset', models.CharField(choices=[('KES', 'KES'), ('USDT', 'USDT')], max_length=20)),
                ('to_asset', models.CharField(choices=[('KES', 'KES'), ('USDT', 'USDT')], max_length=20)),
                ('from_amount', models.DecimalField(decimal_places=8, max_digits=24)),
                ('to_amount', models.DecimalField(decimal_places=8, max_digits=24)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=24)),
                ('reference', models.CharField(max_length=80, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
