# Generated by Django 5.2.17 on 2026-08-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0002_syntheticconversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketCandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default='BTCUSDT', max_length=20)),
                ('timeframe', models.CharField(default='1m', max_length=10)),
                ('bucket_start', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=8, max_digits=24)),
                ('high', models.DecimalField(decimal_places=8, max_digits=24)),
                ('low', models.DecimalField(decimal_places=8, max_digits=24)),
                ('close', models.DecimalField(decimal_places=8, max_digits=24)),
                ('tick_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-bucket_start'],
                'indexes': [models.Index(fields=['symbol', 'timeframe', 'bucket_start'], name='simulator_m_symbol_45240c_idx')],
                'constraints': [models.UniqueConstraint(fields=('symbol', 'timeframe', 'bucket_start'), name='unique_market_candle_bucket')],
            },
        ),
    ]
