# Generated by Django 5.2.17 on 2026-08-19 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0005_remove_position_user_remove_syntheticconversion_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('operation', models.CharField(choices=[('PURCHASE', 'Purchase'), ('WITHDRAWAL', 'Withdrawal')], max_length=20)),
                ('request_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='idempotency_request', to='simulator.wallettransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'operation', 'key'], name='simulator_i_user_id_2b3ed6_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'operation', 'key'), name='unique_user_operation_idempotency_key')],
            },
        ),
    ]
