# Generated by Django 5.2.17 on 2026-08-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0006_idempotencyrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='checkout_request_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='merchant_request_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='result_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='result_description',
            field=models.TextField(blank=True),
        ),
    ]
